spring:
  application:
      name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/QuizZz?autoReconnect=true
    username: root
    password: Password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc

server:
  port: 9000
  contextPath: /auth


      